# Getting all the instances
- name: EC2 facts SSO servers.
  ec2_remote_facts:
    #aws_access_key: "{{access_key}}"
    #aws_secret_key: "{{sec_key}}"
    region: "eu-central-1"
    filters:
      "tag:Deploy-SH": "SO"
  register: so_instances

# Adding the instances
- name: Adding branch 1 web public
  add_host:
        name: "{{ item.private_ip_address }}"
        groups: 'sh-so-servers'
  with_items: "{{ so_instances.instances }}"
