# Getting all the instances
- name: Backuping last version
  win_robocopy:
    src: "{{backup_source_folder}}"
    dest: "{{backup_destination_folder}}"
    recurse: true
    purge: true
    flags: '/E'

# Getting all the instances
- name: Copy to {{destination_folder}}
  win_robocopy:
    src: "{{source_folder}}"
    dest: "{{destination_folder}}"
    recurse: true
    purge: true
    flags: '/E'