############# My Test Deploy ################

- hosts: local
  roles:
     - gather-ec2-facts
     - download-from-s3
  tags: "s3_gather"

- hosts: sh-so-servers
  roles:
#    - download-from-s3
  tags: so-servers