############# My Test Deploy ################

- hosts: local
  roles:
     - gather-ec2-facts
  tags: "s3_gather"

- hosts: sh-so-servers
  roles:
    - download-from-s3
    - move-files
    - clean-deploy-files
  tags: "so-servers-deploy"
